# Don't use language: python; this gives us an unnecessary virtualenv
language: c
# Seems to be needed to prevent hanging in Python 2.7
# https://github.com/travis-ci/travis-ci/issues/6861
sudo: required

env:
  # Build and test package on all supported python version
  - BUILD_TARGET=3.7
  - BUILD_TARGET=3.6

os:
  - linux

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  # yapf is pinned to help make sure we get the same results here as a user does locally.
  - conda install -q -c defaults -c conda-forge conda=4.6 conda-build conda-verify codecov flake8 pep257 yapf==0.25.0
  - conda info -a
  - export LANG=en_US.UTF-8  

before_script:
  - sudo pip install awscli
  - .travis/setup_mosek.sh

script:
  - conda create --name venv_scs python=$BUILD_TARGET
  - conda activate venv_scs
  - pip install 'numpy>=1.16'
  - pip install -r requirements.txt
  - conda install -c mosek mosek==8.1.63
  - python -m unittest
  

# dist: xenial
# language: python

# python:
#   - '3.6.8'

# install:
#   - pip install 'numpy>=1.16'
#   - pip install -r requirements.txt
#   - pip install awscli
#   - pip install -f https://download.mosek.com/stable/wheel/index.html Mosek==8.1.40

# before_script:
#   - .travis/setup_mosek.sh

# script:
#   - pip install coverage
#   - coverage run -m unittest

# after_success:
#   - pip install codecov
#   - codecov

# deploy:
#   provider: pypi
#   user: slacgismo
#   password:
#     secure: pTV4J4fw6i131jCodg/lNODG8psA4BXIkEAvbBWidIGcZyri0YZtipU574lXrBeifotYeearQHDjAkJzEP7ic6Hs8XFJ0CBWBenskX0UdaORbq7/Kr3SkFvOA6fv6vi/a0QJ21Ew21d7082ZUV+dGYe94OqGQoYRSxFppwcuGDO7w631tFIwu8dDu3GhMvzrt3rO/0gfv4mpDMJZw/7SsEIWOQUOGp0WzK5FDy2iYyOfCr2FJJaaolcmG5pC3clqLSHB4PyGeQzgKJ6v6tb6RPYDkL7MgtTrgSxlzznfoIKkaTkn+VEb+aHaUd46JoTMGFvcCe33eWs/SDFJAry27kKGpYfgmA5M+IhvOebEoXMSmJAx/7AzTgPM03UXtD7JzKS/fwj+fftWxomC91Pzh8zes7CWTSGwMLMxuZuKaJWpO2GeeMY63vDKV/5Eunk4/8GyRNFnzBI91G3GZyBzY0a0N0JcDimlTNAytnkw9IitRoEpPbAYi5nRlS3US+C2nkFGvyvTh2vJw009+Zbyk25KTxUn35WMpXEsmAj0GIpdOmG82oAcJFHngO7mDsjS4Nlsls/8zCjWOGg1lEwi+VDu+rnnTgZdI3IPNrbGKVONkJ870Ii4z3SYOgJ/M7onsfCowmu5X8s0etcxHZBIvdqIE/eUGJKHd/Pua2hwBHc=
#   on:
#     all_branches: true
#     tags: true
#   skip_cleanup: true
#   twine_version: 1.13.0
