dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- pip install 'numpy>=1.16'
- pip install -r requirements.txt
script:
- pip install coverage
- coverage run -m unittest
after_success:
- pip install codecov
- codecov
notifications:
  email:
    recipients:
    - tadatoshi.takahashi@slac.stanford.edu
deploy:
  provider: pypi
  user: "slacgismo"
  password:
    secure: sxbXgqaKdhJx8AATYVDTi7zeBTS7WnXCNokoCQG38fbWd3jPQM6cASi2VJ2nnAGQ/Gbr51x+N9OdpZ96sYxuykdmn59Nb/7omk2AALY6hTPXluTDXgLTsRwjb0gUrkE+KJ/maTbx+L8gpFu1AtsDLomwzsaBWV2kbhzZCpqY5WLYZU6uAdDU2CGORUNe5bQO3pyqg6Peo7zLBc6tU6FO9hWlrhd31WLoisIgaDK4YUN5aM4AkE6YlBZjpCfI0UOzCzXoc24IdVSMTWb4f3SqyNDHpJg7CUM7bLaecm9N2ol6XKDslkSo2oSpaVP3fzSGUTkGkFfd5AaFXa1ngmaUJvQXRsa3a3xqzbKVMjz8fxGoTAdoqC3cxl3B+QZJ96jzEBk1bINKYS9TdSKbdrELcP5yyDj+vyR7p7O+5okQryDQ4ReODTaIEp9rcHe/CkiVO3s5kUAzlH2LtWOdXxC0LufCVIH8MWbEP3xxr+iRvK3Zb9Lt5+gdfnlTv+AFo7BP0rULxcEz2pA/zpWyaH6mgL5nl7rOkUrEIm4YuDglnMfr68X+5MSyFWMVm9fC3kSrkaIwG7TdbczzAwNTxoVUKhSq2l/vCO2FbjEZSZY8d8ycCnSdL7NVO60MfE+BjpWRkaeVVq59XP76E9i7jHEe05WKpQKHEqlF9ukU+s9ueUw=
  on:
    all_branches: true
    tags: true
  skip_cleanup: true