language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install numpy
  - pip install -r requirements.txt
  - pip install -f https://download.mosek.com/stable/wheel/index.html Mosek
script:
  - python -m unittest