version: 2

368_config: &368_config
  docker:
    - image: circleci/python:3.6.8

jobs:
  build:
    <<: *368_config
    steps:
      - checkout
      - run:
          name: Install Conda Deps
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p "$HOME"/miniconda
            source /home/circleci/miniconda/etc/profile.d/conda.sh
            conda activate base
            # Conda configuration
            conda config --set always_yes yes --set auto_update_conda false
            # Update conda
            conda update conda
            conda install anaconda-client conda-build
            conda config --set anaconda_upload no                  
      - run:
          name: Build Anaconda Package
          command: |
            source /home/circleci/miniconda/etc/profile.d/conda.sh
            conda activate base
            conda install -c slacgismo solar-data-tools
            conda build . --channel slacgismo --numpy 1.16.4


      # - run:
      #     name: Install Dependencies
      #     command: |
      #       sudo pip install -r requirements.txt
      #       sudo pip install awscli coverage
      #       sudo pip install -f https://download.mosek.com/stable/wheel/index.html Mosek==8.1.43
      
      # - run:
      #     name: Setup Mosek License File
      #     command: |
      #       sudo mkdir /root/mosek
      #       mkdir $HOME/mosek
      #       aws s3 cp s3://slac.gismo.ci.artifacts/mosek.license/mosek.lic $HOME/mosek/mosek.lic
      #       sudo cp $HOME/mosek/mosek.lic /root/mosek/mosek.lic
      
      # - run:
      #     name: Run Unit Tests
      #     command: sudo coverage run -m unittest
  
  # deploy-pypi:
  #   <<: *368_config
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install twine
  #         command: sudo pip install twine

  #     - run:
  #         name: Create the distribution
  #         command: sudo python setup.py sdist bdist_wheel

  #     - run:
  #         name: Push to PyPI
  #         command: sudo twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

  # deploy-conda:
  #   <<: *368_config
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install anaconda client
  #         command: sudo pip install git+https://github.com/Anaconda-Platform/anaconda-client

  #     - run:
  #         name: Login to Anaconda Cloud
  #         command: sudo anaconda login --username $ANACONDA_CLOUD_USERNAME --password $ANACONDA_CLOUD_PASSWORD

  #     - run:
  #         name: Push to Anaconda
  #         command: sudo twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  
            tags:
              only: /.*/
      # - deploy-pypi:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /^v\d+\.\d+\.\d+$/
      #       branches:
      #         ignore: /.*/
      # - deploy-conda:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /^v\d+\.\d+\.\d+$/
      #       branches:
      #         ignore: /.*/
