version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    
    filters:  
      tags:
        only: /.*/
    
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install awscli coverage
            sudo pip install -f https://download.mosek.com/stable/wheel/index.html Mosek==8.1.43
      
      - run:
          name: Setup Mosek License File
          command: |
            sudo mkdir /root/mosek
            mkdir $HOME/mosek
            aws s3 cp s3://slac.gismo.ci.artifacts/mosek.license/mosek.lic $HOME/mosek/mosek.lic
            sudo cp $HOME/mosek/mosek.lic /root/mosek/mosek.lic
      
      - run:
          name: Run Unit Tests
          command: sudo coverage run -m unittest
  
  deploy:
    steps:
      - checkout
      - run:
          name: 'Deploy if tagged on master'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "development" ]]; then
              echo "I'm on the development branch"
            fi


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.\d+\.\d+\.\d+$/

# DEPLOY_ENV=prod ./.circleci/deploy-circle.sh
# deploy:
#   provider: pypi
#   user: slacgismo
#   password:
#     secure: pTV4J4fw6i131jCodg/lNODG8psA4BXIkEAvbBWidIGcZyri0YZtipU574lXrBeifotYeearQHDjAkJzEP7ic6Hs8XFJ0CBWBenskX0UdaORbq7/Kr3SkFvOA6fv6vi/a0QJ21Ew21d7082ZUV+dGYe94OqGQoYRSxFppwcuGDO7w631tFIwu8dDu3GhMvzrt3rO/0gfv4mpDMJZw/7SsEIWOQUOGp0WzK5FDy2iYyOfCr2FJJaaolcmG5pC3clqLSHB4PyGeQzgKJ6v6tb6RPYDkL7MgtTrgSxlzznfoIKkaTkn+VEb+aHaUd46JoTMGFvcCe33eWs/SDFJAry27kKGpYfgmA5M+IhvOebEoXMSmJAx/7AzTgPM03UXtD7JzKS/fwj+fftWxomC91Pzh8zes7CWTSGwMLMxuZuKaJWpO2GeeMY63vDKV/5Eunk4/8GyRNFnzBI91G3GZyBzY0a0N0JcDimlTNAytnkw9IitRoEpPbAYi5nRlS3US+C2nkFGvyvTh2vJw009+Zbyk25KTxUn35WMpXEsmAj0GIpdOmG82oAcJFHngO7mDsjS4Nlsls/8zCjWOGg1lEwi+VDu+rnnTgZdI3IPNrbGKVONkJ870Ii4z3SYOgJ/M7onsfCowmu5X8s0etcxHZBIvdqIE/eUGJKHd/Pua2hwBHc=
