package:
  name: statistical-clear-sky
  version: 0.1.1

source:
  url: https://files.pythonhosted.org/packages/a4/de/ababe0eb251d1e9913d6a91c371382202426dfd3d1516296b50263220b67/statistical-clear-sky-0.1.0.tar.gz

requirements:
  host:
    - python
  run:
    - python
