{% set name = "statistical-clear-sky" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0085f9728abeb90e1624808be9e349e1783aaed118bdeda49ee3a37100ed9b6e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - seaborn
  run:
    - numpy
    - pandas
    - python
    - seaborn

test:
  imports:
    - statistical_clear_sky
    - statistical_clear_sky.iterative_clear_sky

about:
  home: https://github.com/bmeyers/StatisticalClearSky
  license: BSD
  license_family: BSD
  license_file:
  summary: Statistical estimation of a clear sky signal from PV system power data
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
