{% set name = "statistical-clear-sky" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13228d21065ee2067df5d21e0f5a2a1e52abb01e93cb7a4fe9650ea9d1c134fe

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - seaborn
  run:
    - numpy
    - pandas
    - python
    - seaborn

test:
  imports:
    - statistical_clear_sky
    - statistical_clear_sky.algorithm
    - statistical_clear_sky.algorithm.initialization
    - statistical_clear_sky.algorithm.serialization
    - statistical_clear_sky.algorithm.plot
    - statistical_clear_sky.algorithm.util

about:
  home: https://github.com/bmeyers/StatisticalClearSky
  license: BSD
  license_family: BSD
  license_file:
  summary: Statistical estimation of a clear sky signal from PV system power data
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
